### ISSUE TITLE
Help with the nav

### ISSUE THREAD

**Issue by tomchute** [bagseye/startup#1]
Hi, thanks so much for this awesome starter, and the work that must have gone into it!
I have a question regarding the nav. At the moment there's a # in the path in Navbar.js, which means the nav doesn't scroll to the section on the page, or a new page if one is created. I added {item.path} to pull the path from the links.js file, but still having some issues with the new page opening in the same scroll position as the previous page. I wondered if this is expected behaviour, or my setup is causing issues (I have just cloned the repo, with no changes bar the item.path below):
`<ul className={isOpen ? "nav-links show-nav" : "nav-links"}>
        {mainMenuItems.map((item, index) => {
          return (
            <li key={index}>
              <a href={item.path}>{item.text}</a>
            </li>
          )
        })}
      </ul>`

Thanks for any help with this.

**Comment by bagseye** [comment]
Thanks very much.

I've not worked on this template for a while and it is next on my list for some component changes, but the intention was for those Menu Links to jump to the related section, but I think I must've forgotten to do it before submitting this site. 

So for example, `contact.js` has an id of `#contact` and `Navbar.js` would map over each item and update the `href` with the correct id.

Anyway, I've pushed some changes in `Navbar.js` which should hopefully sort this - `href={`#${item.text}`}`

**Comment by tomchute** [comment]
Wow - thank you for amazingly swift response and a fix, really appreciate it.
